# Generated by Django 4.1.13 on 2024-06-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='it_fiels',
            new_name='it_fields',
        ),
    ]
