# Generated by Django 4.1.13 on 2024-06-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='depart',
        ),
    ]
