# Generated by Django 4.1.13 on 2024-06-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maker_app', '0002_delete_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('cv', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
