# Generated by Django 4.1.13 on 2024-06-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_job_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_selection',
            name='image',
        ),
        migrations.AddField(
            model_name='job_selection',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cvc/'),
        ),
    ]
