# Generated by Django 4.1.13 on 2024-06-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_job_selection_image_job_selection_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='candidate',
        ),
    ]
