# Generated by Django 4.1.13 on 2024-06-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_delete_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_selection',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cvs/'),
        ),
    ]
