# Generated by Django 4.1.13 on 2024-06-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_job_selection_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='user',
        ),
        migrations.AddField(
            model_name='register_user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register_user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register_user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
