# Generated by Django 4.1.13 on 2024-06-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_job_selection_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_selection',
            name='username',
        ),
    ]
