# Generated by Django 4.1.13 on 2024-06-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_remove_job_selection_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_selection',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
