# Generated by Django 4.1.13 on 2024-06-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_job_selection_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register_user',
        ),
    ]
